const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('eve', {
  showDirectory:       () => ipcRenderer.send('show-directory'),
  hideDirectory:       () => ipcRenderer.send('hide-directory'),
  toggleDirectory:     () => ipcRenderer.send('toggle-directory'),
  toggleDirectorySize: () => ipcRenderer.send('toggle-directory-size'),

  openAppManager:     () => ipcRenderer.send('open-app-manager'),
  closeAppManager:    () => ipcRenderer.send('close-app-manager'),
  openWindowManager:  () => ipcRenderer.send('open-window-manager'),
  closeWindowManager: () => ipcRenderer.send('close-window-manager'),

  getDisplays:       ()          => ipcRenderer.invoke('get-displays'),
  setOverlayDisplay: (displayId) => ipcRenderer.send('set-overlay-display', { displayId }),

  onDisplaysChanged:      (cb) => ipcRenderer.on('displays-changed',       cb),
  onDirectorySizeChanged: (cb) => ipcRenderer.on('directory-size-changed', cb),

  openVoiceSettings:   () => ipcRenderer.send('open-voice-settings'),
  closeVoiceSettings:  () => ipcRenderer.send('close-voice-settings'),
  snapPanel:           (panel, bounds) => ipcRenderer.send('snap-panel', { panel, bounds }),
  identifyMonitors:    () => ipcRenderer.send('identify-monitors'),
  identifyZones:       () => ipcRenderer.send('identify-zones'),
  dismissZoneOverlay:  () => ipcRenderer.send('dismiss-zone-overlay'),
  identifyWindows:     (payload) => ipcRenderer.send('identify-windows', payload),
  dismissWindowOverlay:() => ipcRenderer.send('dismiss-window-overlay'),
  wmApplyPreset:       (monitorRef, presetKey) => ipcRenderer.send('wm-apply-preset', { monitorRef, presetKey }),
  wmMoveHud:           (monitorRef)            => ipcRenderer.send('wm-move-hud',     { monitorRef }),
  wmSetOrbCorner:      (corner)                => ipcRenderer.send('wm-set-orb-corner', { corner }),
  onLayoutsChanged:    (cb) => ipcRenderer.on('layouts-changed', cb),

  // ── Command Editor ───────────────────────────────────────────────────────
  openCommandEditor:   () => ipcRenderer.send('open-command-editor'),
  closeCommandEditor:  () => ipcRenderer.send('close-command-editor'),
  openPrograms:        () => ipcRenderer.send('open-programs'),
  closePrograms:       () => ipcRenderer.send('close-programs'),
  openMemory:          () => ipcRenderer.send('open-memory'),
  closeMemory:         () => ipcRenderer.send('close-memory'),
  openReminders:       () => ipcRenderer.send('open-reminders'),
  closeReminders:      () => ipcRenderer.send('close-reminders'),
  openIntegrations:    () => ipcRenderer.send('open-integrations'),
  closeIntegrations:   () => ipcRenderer.send('close-integrations'),
  openExternal:        (url) => ipcRenderer.send('open-external', url),
  closeSelf:           () => ipcRenderer.send('close-self'),
  maximizeSelf:        () => ipcRenderer.send('maximize-self'),

  // ── YouTube HUD browser ──────────────────────────────────────────────────
  openYoutube:         () => ipcRenderer.send('open-youtube'),
  youtubeScroll:       (dir)   => ipcRenderer.send('youtube-scroll', dir),
  youtubeNumber:       ()      => ipcRenderer.send('youtube-number'),
  youtubeOpen:         (n)     => ipcRenderer.send('youtube-open', n),
  youtubeSearch:       (query) => ipcRenderer.send('youtube-search', query),
  youtubePlayPause:    ()      => ipcRenderer.send('youtube-playpause'),
  closeYoutube:        ()      => ipcRenderer.send('close-youtube'),
  ceGetCommands:       ()       => ipcRenderer.invoke('command-editor:get-commands'),
  ceSetCommands:       (data)   => ipcRenderer.invoke('command-editor:set-commands', data),
  ceGetApps:           ()       => ipcRenderer.invoke('command-editor:get-apps'),
  ceSetApps:           (data)   => ipcRenderer.invoke('command-editor:set-apps', data),
  ceGetAliases:        ()       => ipcRenderer.invoke('command-editor:get-aliases'),
  ceSetAliases:        (data)   => ipcRenderer.invoke('command-editor:set-aliases', data),
  ceGetBuiltins:       ()       => ipcRenderer.invoke('command-editor:get-builtins'),
  ceBrowseExe:         ()       => ipcRenderer.invoke('command-editor:browse-exe'),
  ceGetRaw:            (key)    => ipcRenderer.invoke('command-editor:get-raw', key),
  ceSetRaw:            (key, text) => ipcRenderer.invoke('command-editor:set-raw', { fileKey: key, text }),
  onCommandsChanged:   (cb) => ipcRenderer.on('commands-changed', cb),
  getVoiceSettings:    () => ipcRenderer.invoke('get-voice-settings'),
  getVoicePresets:     () => ipcRenderer.invoke('get-voice-presets'),
  saveVoicePreset:     (name, params) => ipcRenderer.invoke('save-voice-preset', { name, params }),
  deleteVoicePreset:   (name)         => ipcRenderer.invoke('delete-voice-preset', { name }),

  getTilingLayouts:  ()                       => ipcRenderer.invoke('get-tiling-layouts'),
  setTilingLayout:   (monitorId, monitorData) => ipcRenderer.invoke('set-tiling-layout', { monitorId, monitorData }),
})
